### PR TITLE
Add device

### PR DESCRIPTION
**Pull request by FrancescoSaverioZuppichini**
Now you can pass a `device` and be able to train the model on a GPU!

### CODE REVIEW

**Comment by lucidrains** [comment]
@FrancescoSaverioZuppichini cool! but couldn't you have just done a `learner.to(device)` and pass in `images.to(device)`  in the training loop?

**Comment by FrancescoSaverioZuppichini** [comment]
I tried but it was not working on my setup

**Comment by lucidrains** [comment]
@FrancescoSaverioZuppichini ohhh doh, I think there's an edge case where if you pass in a network already on CUDA to the wrapper, it fails. I've fixed it in the latest commit

```python
import torch
from byol_pytorch import BYOL
from torchvision import models
from tqdm import tqdm

resnet = models.resnet50(pretrained=True).cuda()

learner = BYOL(
    resnet,
    image_size = 256,
    hidden_layer = 'avgpool',
    projection_size = 128,
    projection_hidden_size = 2048,
    moving_average_decay = 0.99
).cuda()

opt = torch.optim.Adam(learner.parameters(), lr=1e-4)

def sample_batch_images():
    return torch.randn(20, 3, 256, 256).cuda()

for _ in tqdm(range(100000)):
    images = sample_batch_images()
    loss = learner(images)
    opt.zero_grad()
    loss.backward()
    print(loss.item())
    opt.step()
    learner.update_moving_average() # update moving average of key encoder
```

Should work now!

**Comment by FrancescoSaverioZuppichini** [comment]
Yes :) Thank you!

**Pull request closed without merging**
