### PR TITLE
Add normalization params as class init params

### PR DESCRIPTION
**Pull request by YoniSchirris**

### CODE REVIEW

**Comment by lucidrains** [comment]
@YoniSchirris hey! If you want to customize your augmentations other than the default, there is already a keyword for that `augment_fn` https://github.com/lucidrains/byol-pytorch#advanced

**Comment by lucidrains** [comment]
@YoniSchirris I think it is probably best to not add anymore keywords to the constructor. The augmentation function can be arbitrarily complex, and its best to leave that up to the user

**Comment by YoniSchirris** [comment]
Fair point @lucidrains , I missed out on that, apologies. Will close the PR

**Comment by lucidrains** [comment]
no problem! thanks for making the PR!

**Pull request closed without merging**
